version: 1.0

stages:
  - name: deploy_stage
    jobs:
      - deploy_backend

jobs:
  deploy_backend:
    steps:
      - npm install -g zcatalyst-cli
      - >-
        catalyst deploy appsail --name backend --build-path "."
        --stack python_3_11 --command "python backend/main.py"
        --token "<< global.CATALYST_TOKEN >>" --verbose
