version: 1.0
pipeline-when:
  equal:
    - "<< event.ref >>"
    - "refs/heads/main"

images:
  python_env:
    image: "python:3.11"

stages:
  - name: deploy_stage
    image: python_env
    jobs:
      - deploy_backend

jobs:
  deploy_backend:
    steps:
      - python3 -m pip install -r requirements.txt
      - catalyst deploy --only appsail
