version: 1.0
pipeline-when:
  equal:
    - "<< event.ref >>"
    - "refs/heads/main"

stages:
  - name: deploy_stage
    jobs:
      - deploy_backend

jobs:
  deploy_backend:
    steps:
      - >-
        catalyst deploy appsail --name backend --build-path "."
        --stack python_3_11 --command "python backend/main.py"
        --verbose
