version: 1.0
pipeline-when:
  equal:
    - << event.ref >>
    - refs/heads/main

jobs:
  deploy_backend:
    steps:
      - pip install -r requirements.txt
      - deploy:
          target: appsail
          config:
            name: backend
            runtime: python3.11
            startup_command: python backend/main.py
